# dashboard/migrations/0001_initial.py
# Generated by Django 5.2 on ...

from django.db import migrations, models

# --- ADD SQL DEFINITIONS HERE ---
# *** Confirm 'dashboard_ohlcvdata_pkey' is correct via \d in psql if possible ***
DROP_DEFAULT_PK = "ALTER TABLE dashboard_ohlcvdata DROP CONSTRAINT IF EXISTS dashboard_ohlcvdata_pkey;"
ADD_DEFAULT_PK = "ALTER TABLE dashboard_ohlcvdata ADD CONSTRAINT dashboard_ohlcvdata_pkey PRIMARY KEY (id);"
ENABLE_TIMESCALE_EXTENSION = "CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;"
CREATE_HYPERTABLE = "SELECT create_hypertable('dashboard_ohlcvdata', 'timestamp', if_not_exists => TRUE);"
ADD_UNIQUE_INDEX = """
    CREATE UNIQUE INDEX IF NOT EXISTS unique_timestamp_ticker_idx
    ON dashboard_ohlcvdata (timestamp, ticker);
"""
DROP_UNIQUE_INDEX = "DROP INDEX IF EXISTS unique_timestamp_ticker_idx;"
ADD_TICKER_TIMESTAMP_INDEX = """
    CREATE INDEX IF NOT EXISTS dashboard_ohlcvdata_ticker_ts_idx
    ON dashboard_ohlcvdata (ticker, timestamp);
"""
DROP_TICKER_TIMESTAMP_INDEX = "DROP INDEX IF EXISTS dashboard_ohlcvdata_ticker_ts_idx;"
DROP_HYPERTABLE_TABLE = "DROP TABLE IF EXISTS dashboard_ohlcvdata;"
# --- END SQL DEFINITIONS ---


class Migration(migrations.Migration):

    initial = True
    dependencies = []

    operations = [
        # --- This CreateModel was generated by makemigrations ---
        migrations.CreateModel(
            name="OHLCVData",
            fields=[
                 ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                 ("timestamp", models.DateTimeField(help_text="The beginning of the time interval (e.g., day) for the OHLCV data.")),
                 ("ticker", models.CharField(help_text="Stock ticker symbol (e.g., AAPL).", max_length=20)),
                 ("open", models.DecimalField(decimal_places=4, help_text="...", max_digits=19)),
                 ("high", models.DecimalField(decimal_places=4, help_text="...", max_digits=19)),
                 ("low", models.DecimalField(decimal_places=4, help_text="...", max_digits=19)),
                 ("close", models.DecimalField(decimal_places=4, help_text="...", max_digits=19)),
                 ("volume", models.BigIntegerField(help_text="...")),
            ],
            options={
                "verbose_name": "OHLCV Data",
                "verbose_name_plural": "OHLCV Data",
                "ordering": ["ticker", "-timestamp"],
            },
        ),
        # --- ADD RunSQL Operations AFTER CreateModel ---
        migrations.RunSQL(
            DROP_DEFAULT_PK,
            reverse_sql=ADD_DEFAULT_PK
        ),
        migrations.RunSQL(
            ENABLE_TIMESCALE_EXTENSION,
            reverse_sql="SELECT 1;"
        ),
        migrations.RunSQL(
            CREATE_HYPERTABLE,
            reverse_sql=DROP_HYPERTABLE_TABLE
        ),
        migrations.RunSQL(
            ADD_UNIQUE_INDEX,
            reverse_sql=DROP_UNIQUE_INDEX
        ),
        migrations.RunSQL(
            ADD_TICKER_TIMESTAMP_INDEX,
            reverse_sql=DROP_TICKER_TIMESTAMP_INDEX
        ),
        # --- End RunSQL Operations ---
    ]
