# Generated by Django 5.2 on 2025-04-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TradeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticker",
                    models.CharField(
                        help_text="Stock ticker symbol (e.g., AAPL)", max_length=20
                    ),
                ),
                (
                    "strategy",
                    models.CharField(
                        help_text="Trading strategy used (e.g., Classic Breakout)",
                        max_length=50,
                    ),
                ),
                (
                    "entry_date",
                    models.DateTimeField(
                        help_text="Date and time when the trade was entered"
                    ),
                ),
                (
                    "exit_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when the trade was exited (can be filled later)",
                        null=True,
                    ),
                ),
                (
                    "entry_price",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Price at which the trade was entered",
                        max_digits=19,
                    ),
                ),
                (
                    "exit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Price at which the trade was exited (can be filled later)",
                        max_digits=19,
                        null=True,
                    ),
                ),
                (
                    "initial_stop_loss",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Initial stop loss price",
                        max_digits=19,
                    ),
                ),
                (
                    "planned_target",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Target price for the trade (projected exit)",
                        max_digits=19,
                        null=True,
                    ),
                ),
                (
                    "position_size",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Size of the position (number of shares/contracts)",
                        max_digits=19,
                    ),
                ),
                (
                    "suggested_position_size",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Calculated suggested position size based on risk parameters",
                        max_digits=19,
                        null=True,
                    ),
                ),
                (
                    "pnl",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Profit or loss from the trade (can be calculated)",
                        max_digits=19,
                        null=True,
                    ),
                ),
                (
                    "planned_rr_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Planned risk-reward ratio for the trade",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "user_risk_percent",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage of account willing to risk on this trade",
                        max_digits=5,
                    ),
                ),
                (
                    "account_capital_at_trade",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Account capital at the time of the trade",
                        max_digits=19,
                    ),
                ),
                (
                    "rationale",
                    models.TextField(help_text="Reasons for entering the trade"),
                ),
                (
                    "emotion_pre",
                    models.TextField(
                        blank=True,
                        help_text="Emotional state before entering the trade",
                        null=True,
                    ),
                ),
                (
                    "emotion_during",
                    models.TextField(
                        blank=True,
                        help_text="Emotional state while in the trade",
                        null=True,
                    ),
                ),
                (
                    "emotion_post",
                    models.TextField(
                        blank=True,
                        help_text="Emotional state after exiting the trade",
                        null=True,
                    ),
                ),
                (
                    "mistakes",
                    models.TextField(
                        blank=True,
                        help_text="Mistakes made during the trade",
                        null=True,
                    ),
                ),
                (
                    "lessons",
                    models.TextField(
                        blank=True,
                        help_text="Lessons learned from the trade",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Trade Log",
                "verbose_name_plural": "Trade Logs",
                "ordering": ["-entry_date"],
            },
        ),
    ]
